# Generated by Django 4.1.7 on 2023-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micontenido', '0002_cupones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupones',
            name='cant_usado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
