# Generated by Django 4.1.7 on 2023-06-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_estilo_color_fondo_post_estilo_color_letra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='estilo_color_fondo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='estilo_color_letra',
        ),
        migrations.RemoveField(
            model_name='post',
            name='estilo_fuente_letra',
        ),
        migrations.RemoveField(
            model_name='post',
            name='estilo_tamano_letra_cuerpo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='estilo_tamano_letra_titulo',
        ),
    ]
