# Generated by Django 4.1.7 on 2023-04-04 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(blank=True, null=True, upload_to='categoria/iconos/')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='usuarios_cursando',
            field=models.ManyToManyField(blank=True, related_name='cursos_cursando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=10000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio', models.FloatField()),
                ('cantidad_videos', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='curso/imagenes/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.categoria')),
                ('usuarios_cursando', models.ManyToManyField(blank=True, related_name='talleres_cursando', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curso.categoria'),
            preserve_default=False,
        ),
    ]
