# Generated by Django 4.1.7 on 2023-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_categoria_curso_usuarios_cursando_taller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=1000)),
                ('tipo_archivo', models.CharField(max_length=250)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
    ]
