# Generated by Django 4.1.7 on 2023-06-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_video_link_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='material/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_archivo',
            field=models.CharField(choices=[('<i class="bi bi-file-earmark-word-fill"></i>', 'Word'), ('<i class="bi bi-file-earmark-pdf-fill"></i>', 'PDF'), ('<i class="bi bi-file-ppt-fill"></i>', 'PowerPoint'), ('<i class="bi bi-file-earmark-slides-fill"></i>', 'Video'), ('<i class="bi bi-file-image-fill"></i>', 'Imagen'), ('<i class="bi bi-file-earmark-richtext-fill"></i>', 'Otro')], max_length=2000),
        ),
    ]
