# Generated by Django 4.1.7 on 2023-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_material_archivo_alter_material_tipo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo_archivo',
            field=models.CharField(choices=[('word', 'Word'), ('pdf', 'PDF'), ('pp', 'PowerPoint'), ('video', 'Video'), ('img', 'Imagen'), ('otro', 'Otro')], max_length=2000),
        ),
    ]
