# Generated by Django 4.1.7 on 2023-06-22 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_material_tipo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.taller'),
        ),
    ]
