# Generated by Django 4.1.7 on 2023-06-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_material_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='taller_pertenece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.taller'),
        ),
        migrations.AlterField(
            model_name='material',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='video',
            name='curso_pertenece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
