# Generated by Django 4.1.7 on 2023-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_video_taller_pertenece_alter_material_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_collection',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
