# Generated by Django 4.1.7 on 2023-06-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_curso_id_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='id_collection',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
